"use client";
// AUTO-GENERATED BY scripts/generate-registry.ts — DO NOT EDIT DIRECTLY
import React from "react";
import { REGISTRY_DATA, RegistryItemData } from "./registry-data";
import { default as FloatingDockerComponent } from "../../../registry/blocks/floating-docker/files/floating-docker";
import { default as InteractiveCalendarComponent } from "../../../registry/blocks/interactive-calendar/files/interactive-calendar";
import { DEMO_MARKED_DATES as _CalendarDemoData } from "../../../registry/blocks/interactive-calendar/files/interactive-calendar";
import { default as SocialAuthButtonsComponent } from "../../../registry/blocks/social-auth-buttons/files/social-auth-buttons";
import { default as TrendChartComponent } from "../../../registry/blocks/trend-chart/files/trend-chart";

export interface RegistryWebItem extends RegistryItemData {
  Component: React.ComponentType;
}

export type BlockItem = RegistryWebItem;

export const REGISTRY_ITEMS: RegistryWebItem[] = [
  {
    ...REGISTRY_DATA.find((item) => item.slug === "floating-docker")!,
    Component: FloatingDockerComponent as React.ComponentType,
  },
  {
    ...REGISTRY_DATA.find((item) => item.slug === "interactive-calendar")!,
    Component: (() => {
      const Wrapped = (props: any) => <InteractiveCalendarComponent markedDates={_CalendarDemoData} {...props} />;
      Wrapped.displayName = "InteractiveCalendarComponentWrapped";
      return Wrapped;
    })() as React.ComponentType,
  },
  {
    ...REGISTRY_DATA.find((item) => item.slug === "social-auth-buttons")!,
    Component: SocialAuthButtonsComponent as React.ComponentType,
  },
  {
    ...REGISTRY_DATA.find((item) => item.slug === "trend-chart")!,
    Component: TrendChartComponent as React.ComponentType,
  }
];

export const BLOCKS_DATA: BlockItem[] = REGISTRY_ITEMS;
