import fs from "node:fs";
import path from "node:path";
import { RegistryItemSchema } from "../packages/registry/src/schema";

const ROOT = process.cwd();
const REGISTRY_DIR = path.join(ROOT, "registry");
const OUTPUT_REGISTRY_JSON = path.join(REGISTRY_DIR, "registry.json");
const OUTPUT_WEB_DATA = path.join(ROOT, "apps", "web", "data", "blocks.tsx");

function generateRegistry() {
  console.log("🔨 Generating Registry from:", REGISTRY_DIR);

  const allItems: any[] = [];
  const imports: string[] = [];
  const exportedItems: string[] = [];

  for (const type of ["blocks", "screens"] as const) {
    const typeDir = path.join(REGISTRY_DIR, type);
    if (!fs.existsSync(typeDir)) continue;

    const subdirs = fs
      .readdirSync(typeDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name);

    for (const slug of subdirs) {
      const itemDir = path.join(typeDir, slug);
      const metaPath = path.join(itemDir, "registry.json");

      if (!fs.existsSync(metaPath)) continue;

      const meta = JSON.parse(fs.readFileSync(metaPath, "utf-8"));
      const parsed = RegistryItemSchema.parse(meta);

      allItems.push(parsed);

      // Read primary component file
      const primaryFile = parsed.files[0];
      const primaryFilePath = path.join(itemDir, primaryFile.path);
      const code = fs.existsSync(primaryFilePath)
        ? fs.readFileSync(primaryFilePath, "utf-8")
        : "";

      const compName =
        slug
          .split("-")
          .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
          .join("") + "Component";

      // Relative import from apps/web/data/blocks.tsx to registry/
      const relImportPath = `../../../registry/${type}/${slug}/${primaryFile.path.replace(/\.tsx$/, "")}`;
      imports.push(`import { default as ${compName} } from "${relImportPath}";`);

      exportedItems.push(`  {
    slug: "${slug}",
    name: "${parsed.name}",
    title: ${JSON.stringify(parsed.title)},
    description: ${JSON.stringify(parsed.description)},
    type: "${parsed.type}",
    category: "${parsed.category}",
    author: ${JSON.stringify(parsed.author)},
    version: "${parsed.version}",
    platforms: ${JSON.stringify(parsed.platforms)},
    framework: "${parsed.framework}",
    styling: ${JSON.stringify(parsed.styling)},
    dependencies: ${JSON.stringify(parsed.dependencies)},
    registryDependencies: ${JSON.stringify(parsed.registryDependencies)},
    code: ${JSON.stringify(code)},
    Component: ${compName} as React.ComponentType,
  }`);
    }
  }

  // 1. Write root registry/registry.json
  const manifest = {
    version: "1.0.0",
    generatedAt: new Date().toISOString(),
    items: allItems,
  };

  fs.writeFileSync(
    OUTPUT_REGISTRY_JSON,
    JSON.stringify(manifest, null, 2),
    "utf-8"
  );
  console.log(`✓ Generated ${OUTPUT_REGISTRY_JSON} with ${allItems.length} items.`);

  // 2. Ensure apps/web/data exists
  const webDataDir = path.dirname(OUTPUT_WEB_DATA);
  if (!fs.existsSync(webDataDir)) {
    fs.mkdirSync(webDataDir, { recursive: true });
  }

  // 3. Write apps/web/data/blocks.tsx
  const tsContent = `// AUTO-GENERATED BY scripts/generate-registry.ts — DO NOT EDIT DIRECTLY
import React from "react";
${imports.join("\n")}

export interface RegistryWebItem {
  slug: string;
  name: string;
  title: string;
  description: string;
  type: "block" | "screen";
  category: string;
  author: string;
  version: string;
  platforms: string[];
  framework: string;
  styling: string[];
  dependencies: string[];
  registryDependencies: string[];
  code: string;
  Component: React.ComponentType;
}

export type BlockItem = RegistryWebItem;

export const REGISTRY_ITEMS: RegistryWebItem[] = [
${exportedItems.join(",\n")}
];

export const BLOCKS_DATA: BlockItem[] = REGISTRY_ITEMS;
`;

  fs.writeFileSync(OUTPUT_WEB_DATA, tsContent, "utf-8");
  console.log(`✓ Generated ${OUTPUT_WEB_DATA}`);
}

generateRegistry();
